services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      BOT_USERNAME: ${BOT_USERNAME}
      BOT_TOKEN: ${BOT_TOKEN}

      DB_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      BOT_DEBUG_ENABLED: ${BOT_DEBUG_ENABLED}
      BOT_DEBUG_CHAT_ID: ${BOT_DEBUG_CHAT_ID}

      D2C_SERVICE_ENABLE: ${D2C_SERVICE_ENABLE}
      D2C_SERVICE_URL: ${D2C_SERVICE_URL}
    ports:
      - "8080:8080"

volumes:
  pg_data:
